### ISSUE TITLE
<class 'tessa.price.types.SymbolNotFoundError'>, 'occurred.' when using price_latest

### ISSUE THREAD

**Issue by f1xxxer** [ymyke/tessa#14]
Hello, 

at the moment I'm using tessa `0.4.1` to get the etf prices from yahoo.

When I'm trying to get the price for the Yahoo ticker like **MOGL.AX**  I get an error `SymbolNotFoundError("No symbol found on source 'yahoo' for query 'MOGL.AX'.")`  

However, when I go to the yahoo finance and enter this ticker in search there's no problem with finding it. 

To confirm is it not related to the rate limiting I was changing IP addresses (using my mobile).

The issues is happening since two weeks, at least for me.

Any advice?

UPD. The issue is most likely related to https://github.com/ranaroussi/yfinance/issues/1268 - I will keep an eye

**Comment by ymyke** [comment]
Thanks for reporting this. This was due to the way tessa used to find out a ticker's currency.

Please update to the latest version (0.5.0) which should fix this – and also make things much more performant than before. Note that it requires to also upgrade yfinance to at least v0.2.3.

Can you please confirm that this resolves your issue?

**Comment by f1xxxer** [comment]
yes, it is all now fixed and seems to be definitely much more performant. Thanks!
