### ISSUE TITLE
price_latest yeilds same value in same context

### ISSUE THREAD

**Issue by Dainerx** [ymyke/tessa#18]
Hey, so the issue is pretty simple. I believe, `price_latest()` is somehow caching per context. Iterating inside a loop and printing the stock value, will always yield same result. The value always remain the same, even when I tried printing each 5 minutes. **However**, killing the script and re-running yield different value.

`Version: 0.8.0`
`Python 3.10.7`

Both code snippets below produce the bug. 

## Code Snippet 1
```python 
while True:
    for _ in range(1):
        print(Symbol("GOOGL").price_latest().price, "\n")
        time.sleep(20)
```

## Code Snippet 2
```python
from tessa import Symbol
from apscheduler.schedulers.background import BlockingScheduler

sched = BlockingScheduler()
sched.add_job(lambda: print(Symbol("GOOGL").price_latest().price, "\n"), 'interval', seconds = 60)
sched.start()
```

I don't know what I am doing wrong, I could not find any relevant documentation for this issue. I saw that you use a rate limiter, could this be related?

**Comment by ymyke** [comment]
Yes, tessa does caching on the `price_history` function. See here: https://github.com/ymyke/tessa/blob/5383ebc4d54efffbd878dee705213aed19c2b562/tessa/price/price.py#L21C1-L21C1

There is an issue with long-running applications, because the cache never expires. See also #2 . 

This shouldn't matter as long as your use case doesn't rely on "real-time" (as far as the underlying services provide these) price information or your app doesn't run for days at a time.

As a workaround to guarantee to always get fresh information, you can clear the cache at relevant spots in your code:

```python
tessa.price_history.cache_clear()
```

HTH!
