### ISSUE TITLE
Tessa not working on Google Colab

### ISSUE THREAD

**Issue by firmai** [ymyke/tessa#7]
I am in a simple colab environment, and can't get the pypi install to work, let me know if you understand whats going on. 
![image](https://user-images.githubusercontent.com/26666267/172392357-f26f9bac-3b8a-41f6-af67-78f777b6e55a.png)

**Comment by ymyke** [comment]
Strange. That's from a Jupyter notebook? What happens if you leave out the version specification?

**Comment by firmai** [comment]
Same problem when I leave out the version specification, can you replicate it on Colab?

**Comment by ymyke** [comment]
I gave this a try now and I get the same error as you in Colab. I assume the issue is because Colab runs Python v3.6 whereas tessa currently requires v3.9. – I will check if I can make this more lenient. See also https://github.com/ymyke/tessa/issues/8

**Comment by ymyke** [comment]
Turns out that Google Colab runs Python 3.7. I just released v0.3.1 which should work with >=3.7, <3.10. I tested with Colab and it works there too.

(Nonrelated, but maybe useful in case you ever need to upgrade the Python environment in Colab: https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version)

**Comment by ymyke** [comment]
I published v0.3.2 just now, which should finally work in Colab. Can you confirm, @danilogalisteu ?

**Comment by danilogalisteu** [comment]
v0.3.2 is working in Google Colab with Python 3.7.13. I'm not able to test on Python 3.9 at the moment. Thanks!

**Comment by ymyke** [comment]
Great, thanks!
