### ISSUE TITLE
Compatibility with yfinance / yahoofinance ?

### ISSUE THREAD

**Issue by JuCarm** [ymyke/tessa#9]
I would love to have compatibility with yfinance / yahoofinance.
By that, I mean being able to replace calls to yfinance / yahoofinance by calls to investpy / tessa without having to modify the arguments.

Reason : a lot of investing python scripts are available based on yfinance / yahoofinance, I'd like to be able to reuse them as easily as possible with investpy / tessa, where there are lots more financial assets.

**Comment by ymyke** [comment]
Thanks for the suggestion. Can you give a couple of examples what this would look like? What kinds of function calls in yfinance would you map to what kinds in tessa?

Not sure if a project deciding to switch from yfinance to tessa wouldn't be better off making the real changes rather than using a wrapper...

**Comment by ymyke** [comment]
Any comments, @JuCarm ?

**Comment by ymyke** [comment]
I'll close this now but feel free to comment if you like and I'll reconsider. (Or go ahead and submit a PR.)
